### ISSUE TITLE
Crashed with Dynamic Surroundings due to unknown error

### ISSUE THREAD

**Issue by NobodyHere-rrr** [jbredwards/Subaquatic#44]
### **System Details**
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5587726000 bytes (5328 MB) / 11239337984 bytes (10718 MB) up to 16750411776 bytes (15974 MB)
  JVM Flags: 18 total; -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=8 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+UseFastAccessorMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx16384m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.10 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G6_pre1

### **Versions**
Subaquatic: 1.1.0
Fluidlogged API: 2.2.4
Assetmover: 2.5
Dynamic Surroundings: 3.6.3

### **Crash Report**
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Surroundings (dsurround)
Caused by: java.lang.VerifyError: Bad type on operand stack in putfield
Exception Details:
  Location:
    net/minecraft/client/particle/ParticleDrip.func_189213_a()V @59: putfield
  Reason:
    Type float (current frame, stack[2]) is not assignable to 'net/minecraft/client/particle/ParticleDrip' (constant pool 44)
  Current Frame:
    bci: @59
    flags: { }
    locals: { 'net/minecraft/client/particle/ParticleDrip' }
    stack: { 'net/minecraft/client/particle/ParticleDrip', float, float, float }
  Bytecode:
    0x0000000: 2a2a b400 60b5 0063 2a2a b400 66b5 0069
    0x0000010: 2a2a b400 6cb5 006f 2ab4 0042 b200 23a6
    0x0000020: 0006 a700 2f2a 1224 b500 282a 1270 1028
    0x0000030: 2ab4 0044 6410 1060 8612 29b5 002c 2a12
    0x0000040: 7110 282a b400 4464 1008 6086 122d b500
    0x0000050: 302a 59b4 001b 2ab4 0040 8d67 b500 1b2a
    0x0000060: 59b4 0044 5a04 64b5 0044 9e00 302a 59b4
    0x0000070: 0018 1400 726b b500 182a 59b4 001b 1400
    0x0000080: 726b b500 1b2a 59b4 001e 1400 726b b500
    0x0000090: 1e2a 1071 b600 37a7 0009 2a10 70b6 0037
    0x00000a0: 2a2a b400 182a b400 1b2a b400 1eb6 0077
    0x00000b0: 2a59 b400 1814 0078 6bb5 0018 2a59 b400
    0x00000c0: 1b14 0078 6bb5 001b 2a59 b400 1e14 0078
    0x00000d0: 6bb5 001e 2a59 b400 535a 0464 b500 539d
    0x00000e0: 0007 2ab6 007c 2ab4 0080 9900 4e2a b400
    0x00000f0: 42b2 0023 a600 262a b600 7c2a b400 83b2
    0x0000100: 0089 2ab4 0060 2ab4 0066 2ab4 006c 0e0e
    0x0000110: 0e03 bc0a b600 8fa7 0009 2a10 72b6 0037
    0x0000120: 2a59 b400 1814 0090 6bb5 0018 2a59 b400
    0x0000130: 1e14 0090 6bb5 001e bb00 9359 2ab4 0060
    0x0000140: 2ab4 0066 2ab4 006c b700 954c 2ab4 0083
    0x0000150: 2bb8 009b 4d2c b900 a101 004e 2db6 00a5
    0x0000160: 9a00 0a2d b600 a899 003c 0e39 042c b900
    0x0000170: ac01 00c1 00ae 9900 102c b800 b4b6 00b8
    0x0000180: b800 bc8d 3904 2ab4 0066 b800 c204 6087
    0x0000190: 1804 6739 062a b400 6618 0698 9c00 072a
    0x00001a0: b600 7cb1                              
  Stackmap Table:
    same_frame(@37)
    same_frame(@81)
    same_frame_extended(@154)
    same_frame(@160)
    same_frame_extended(@230)
    same_frame(@282)
    same_frame(@288)
    same_frame(@312)
    append_frame(@362,Top,Object[#157])
    full_frame(@390,{Object[#2],Top,Top,Top,Double},{})
    full_frame(@419,{},{})

    at org.orecruncher.dsurround.proxy.ProxyClient.init(ProxyClient.java:126)
    at org.orecruncher.dsurround.ModBase.init(ModBase.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(ModMixinLoader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandlerMixin.java:336)
    at net.minecraft.client.Minecraft.init(MinecraftMixin.java:535)
    at net.minecraft.client.Minecraft.run(MinecraftMixin.java:8601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

### **Extra Informations**
When you only add Dynamic Surroundings and Subaquatic, Minecraft won't crash.
Full Crash Report: https://paste.ubuntu.com/p/Fc6WmXq3CY/

**Comment by GrandeMalum** [comment]
I'm having the same issue with a different mod pack. DynamicSorroundings is present in my mod pack as well. So I can confirm this incompatibility.

**Comment by jbredwards** [comment]
This doesn't look like a dynamic surroundings conflict, as that mod doesn't make any changes to the `ParticleDrip` class.
> I'm having the same issue with a different mod pack. DynamicSorroundings is present in my mod pack as well. So I can confirm this incompatibility.

@GrandeMalum can you tell me what modpack you're using, so I don't have to install each mod individually for testing? 😅

**Comment by jbredwards** [comment]
I believe this should be fixed with the v1.2.0 update, would someone having this issue mind confirming this for me?

**Comment by jbredwards** [comment]
marking this as fixed, if it isn't let me know and provide more info (like the modpack being used)
