### ISSUE TITLE
unable run this mod at server

### ISSUE THREAD

**Issue by DJQ28** [jbredwards/Subaquatic#62]
I was able to start and successfully run the game on the client side while playing this module, but encountered a startup failure on the server side.
details:
[15:32:22] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [CatServer-090a6ffb-universal.jar:git-CatServer-1.12.2-090a6ffb]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [CatServer-090a6ffb-universal.jar:git-CatServer-1.12.2-090a6ffb]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
        at catserver.server.CatServerLaunch.main(CatServerLaunch.java:17) [CatServer-090a6ffb-universal.jar:git-CatServer-1.12.2-090a6ffb]
Caused by: java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/entity/Entity.func_70091_d(Lnet/minecraft/entity/MoverType;DDD)V @1922: aload
  Reason:
    Type integer (current frame, locals[71]) is not assignable to reference type
  Current Frame:
    bci: @1922
    flags: { }
    locals: { 'net/minecraft/entity/Entity', 'net/minecraft/entity/MoverType', double, double_2nd, double, double_2nd, double, double_2nd, top, top, top, double, double_2nd, top, top, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, top, top, 'java/util/List', 'net/minecraft/util/math/AxisAlignedBB', integer, integer, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, integer, integer, 'net/minecraft/util/math/BlockPos', 'net/minecraft/block/state/IBlockState' }
    stack: { 'net/minecraft/block/state/IBlockState' }
  Bytecode:
    0x0000000: b203 15b6 031a 2ab4 031c 9900 1a2a 2ab6
    0x0000010: 01f1 2818 0418 06b6 02ff b601 ed2a b603
    0x0000020: 1fa7 0adb 2ab6 0322 a700 293a 0819 0813
    0x0000030: 0324 b803 2a3a 0919 0913 032c b603 303a
    0x0000040: 0a2a 190a b603 34bb 0336 5919 09b7 0339
    0x0000050: bf28 0e97 9a00 2018 040e 979a 0019 1806
    0x0000060: 0e97 9a00 122a b603 3c99 000b 2ab6 026b
    0x0000070: 9900 04b1 2bb2 033f a600 f92a b400 e0b6
    0x0000080: 0343 370b 160b 2ab4 0345 9499 0011 2ab4
    0x0000090: 015a 0eb8 034b 2a16 0bb5 0345 280e 9799
    0x00000a0: 0042 b203 4fb6 0352 360a 282a b401 5a15
    0x00000b0: 0a31 6314 0353 1403 55b8 035a 390d 180d
    0x00000c0: 2ab4 015a 150a 3167 492a b401 5a15 0a18
    0x00000d0: 0d52 28b8 0360 1403 6198 9d00 04b1 a700
    0x00000e0: 9318 040e 9799 0045 b203 65b6 0352 360a
    0x00000f0: 1804 2ab4 015a 150a 3163 1403 5314 0355
    0x0000100: b803 5a39 0d18 0d2a b401 5a15 0a31 6739
    0x0000110: 042a b401 5a15 0a18 0d52 1804 b803 6014
    0x0000120: 0361 989d 0004 b1a7 004a 1806 0e97 9a00
    0x0000130: 04b1 b203 67b6 0352 360a 1806 2ab4 015a
    0x0000140: 150a 3163 1403 5314 0355 b803 5a39 0d18
    0x0000150: 0d2a b401 5a15 0a31 6739 062a b401 5a15
    0x0000160: 0a18 0d52 1806 b803 6014 0361 989d 0004
    0x0000170: b12a b400 e0b4 025b 1303 69b6 0262 2ab4
    0x0000180: 01e2 390b 2ab4 01e4 390f 2ab4 01e6 3911
    0x0000190: 2ab4 036b 9900 2d2a 03b5 036b 2814 036c
    0x00001a0: 6b49 1804 1403 6e6b 3904 1806 1403 6c6b
    0x00001b0: 3906 2a0e b503 712a 0eb5 0373 2a0e b503
    0x00001c0: 7528 3913 1804 3915 1806 3917 2bb2 0203
    0x00001d0: a500 0a2b b203 78a6 0165 2ab4 037a 9901
    0x00001e0: 5e2a b603 7d99 0157 2ac1 01a1 9901 5014
    0x00001f0: 037e 3919 280e 9799 0052 2ab4 00e0 2a2a
    0x0000200: b601 f128 2ab4 0381 768d 0eb6 02ff b603
    0x0000210: 07b9 030c 0100 9900 3328 1403 7e98 9c00
    0x0000220: 1028 1403 8297 9b00 080e 49a7 0018 280e
    0x0000230: 979e 000c 2814 037e 6749 a700 0928 1403
    0x0000240: 7e63 4928 3913 a7ff ae18 060e 9799 005c
    0x0000250: 2ab4 00e0 2a2a b601 f10e 2ab4 0381 768d
    0x0000260: 1806 b602 ffb6 0307 b903 0c01 0099 003c
    0x0000270: 1806 1403 7e98 9c00 1218 0614 0382 979b
    0x0000280: 0009 0e39 06a7 001d 1806 0e97 9e00 0e18
    0x0000290: 0614 037e 6739 06a7 000b 1806 1403 7e63
    0x00002a0: 3906 1806 3917 a7ff a328 0e97 9900 9018
    0x00002b0: 060e 9799 0089 2ab4 00e0 2a2a b601 f128
    0x00002c0: 2ab4 0381 768d 1806 b602 ffb6 0307 b903
    0x00002d0: 0c01 0099 0069 2814 037e 989c 0010 2814
    0x00002e0: 0382 979b 0008 0e49 a700 1828 0e97 9e00
    0x00002f0: 0c28 1403 7e67 49a7 0009 2814 037e 6349
    0x0000300: 2839 1318 0614 037e 989c 0012 1806 1403
    0x0000310: 8297 9b00 090e 3906 a700 1d18 060e 979e
    0x0000320: 000e 1806 1403 7e67 3906 a700 0b18 0614
    0x0000330: 037e 6339 0618 0639 17a7 ff70 2ab4 00e0
    0x0000340: 2a2a b601 f128 1804 1806 b603 86b6 0307
    0x0000350: 3a1b 2ab6 01f1 3a1c 1804 0e97 9900 4203
    0x0000360: 361d 191b b903 8701 0036 1e15 1d15 1ea2
    0x0000370: 0020 191b 151d b903 8b02 00c0 01e0 2ab6
    0x0000380: 01f1 1804 b603 8f39 0484 1d01 a7ff df2a
    0x0000390: 2ab6 01f1 0e18 040e b602 ffb6 01ed 280e
    0x00003a0: 9799 0045 0336 1d19 1bb9 0387 0100 361e
    0x00003b0: 151d 151e a200 1e19 1b15 1db9 038b 0200
    0x00003c0: c001 e02a b601 f128 b603 9249 841d 01a7
    0x00003d0: ffe1 280e 9799 0011 2a2a b601 f128 0e0e
    0x00003e0: b602 ffb6 01ed 1806 0e97 9900 4903 361d
    0x00003f0: 191b b903 8701 0036 1e15 1d15 1ea2 0020
    0x0000400: 191b 151d b903 8b02 00c0 01e0 2ab6 01f1
    0x0000410: 1806 b603 9539 0684 1d01 a7ff df18 060e
    0x0000420: 9799 0012 2a2a b601 f10e 0e18 06b6 02ff
    0x0000430: b601 ed2a b403 7a9a 0012 1815 1804 9799
    0x0000440: 000e 1815 0e98 9c00 0704 a700 0403 361d
    0x0000450: 2ab4 0381 0b95 9e02 8315 1d99 027e 1813
    0x0000460: 2897 9a00 0b18 1718 0697 9902 6f28 391f
    0x0000470: 1804 3921 1806 3923 2ab6 01f1 3a25 2a19
    0x0000480: 1cb6 01ed 2ab4 0381 8d39 042a b400 e02a
    0x0000490: 2ab6 01f1 1813 1804 1817 b603 86b6 0307
    0x00004a0: 3a26 2ab6 01f1 3a27 1927 1813 0e18 17b6
    0x00004b0: 0386 3a28 1804 3929 0336 2b19 26b9 0387
    0x00004c0: 0100 362c 152b 152c a200 1e19 2615 2bb9
    0x00004d0: 038b 0200 c001 e019 2818 29b6 038f 3929
    0x00004e0: 842b 01a7 ffe1 1927 0e18 290e b602 ff3a
    0x00004f0: 2718 1339 2d03 362f 1926 b903 8701 0036
    0x0000500: 3015 2f15 30a2 001e 1926 152f b903 8b02
    0x0000510: 00c0 01e0 1927 182d b603 9239 2d84 2f01
    0x0000520: a7ff e119 2718 2d0e 0eb6 02ff 3a27 1817
    0x0000530: 3931 0336 3319 26b9 0387 0100 3634 1533
    0x0000540: 1534 a200 1e19 2615 33b9 038b 0200 c001
    0x0000550: e019 2718 31b6 0395 3931 8433 01a7 ffe1
    0x0000560: 1927 0e0e 1831 b602 ff3a 272a b601 f13a
    0x0000570: 3418 0439 3503 3637 1926 b903 8701 0036
    0x0000580: 3815 3715 38a2 001e 1926 1537 b903 8b02
    0x0000590: 00c0 01e0 1934 1835 b603 8f39 3584 3701
    0x00005a0: a7ff e119 340e 1835 0eb6 02ff 3a34 1813
    0x00005b0: 3939 0336 3b19 26b9 0387 0100 363c 153b
    0x00005c0: 153c a200 1e19 2615 3bb9 038b 0200 c001
    0x00005d0: e019 3418 39b6 0392 3939 843b 01a7 ffe1
    0x00005e0: 1934 1839 0e0e b602 ff3a 3418 1739 3d03
    0x00005f0: 363f 1926 b903 8701 0036 4015 3f15 40a2
    0x0000600: 001e 1926 153f b903 8b02 00c0 01e0 1934
    0x0000610: 183d b603 9539 3d84 3f01 a7ff e119 340e
    0x0000620: 0e18 3db6 02ff 3a34 182d 182d 6b18 3118
    0x0000630: 316b 6339 4118 3918 396b 183d 183d 6b63
    0x0000640: 3943 1841 1843 979e 0018 182d 4918 3139
    0x0000650: 0618 2977 3904 2a19 27b6 01ed a700 1518
    0x0000660: 3949 183d 3906 1835 7739 042a 1934 b601
    0x0000670: ed03 3645 1926 b903 8701 0036 4615 4515
    0x0000680: 46a2 0020 1926 1545 b903 8b02 00c0 01e0
    0x0000690: 2ab6 01f1 1804 b603 8f39 0484 4501 a7ff
    0x00006a0: df2a 2ab6 01f1 0e18 040e b602 ffb6 01ed
    0x00006b0: 181f 181f 6b18 2318 236b 6328 286b 1806
    0x00006c0: 1806 6b63 979b 0014 181f 4918 2139 0418
    0x00006d0: 2339 062a 1925 b601 ed2a b400 e0b4 025b
    0x00006e0: b602 8a2a b400 e0b4 025b 1303 97b6 0262
    0x00006f0: 2ab6 031f 2a18 1328 979a 000b 1817 1806
    0x0000700: 9799 0007 04a7 0004 03b5 0399 2a18 1518
    0x0000710: 0497 9900 0704 a700 0403 b503 9b2a 2ab4
    0x0000720: 039b 9900 0e18 150e 989c 0007 04a7 0004
    0x0000730: 03b5 037a 2a2a b403 999a 000a 2ab4 039b
    0x0000740: 9900 0704 a700 0403 b503 9d2a b401 e2b8
    0x0000750: 03a1 361e 2ab4 01e4 b803 a136 472a b401
    0x0000760: e6b8 03a1 3648 bb00 1c59 151e 1547 1548
    0x0000770: b703 a43a 492a b400 e019 49b6 03a8 3a4a
    0x0000780: 194a 1947 2ab8 03ae 9900 2a19 49b6 03b2
    0x0000790: 3a4b 2ab4 00e0 194b b603 a83a 2519 25b9
    0x00007a0: 03b8 0100 3a26 0499 000b 1925 3a4a 194b
    0x00007b0: 3a49 2a18 042a b403 7a19 4a19 49b6 03be
    0x00007c0: 1813 2897 9900 082a 0eb5 0371 1817 1806
    0x00007d0: 9799 0008 2a0e b503 7519 4ab9 03b8 0100
    0x00007e0: 3a4b 1815 1804 9799 000d 194b 2ab4 00e0
    0x00007f0: 2ab6 03c2 2ab4 0399 9900 b92a b602 30c1
    0x0000800: 03c4 9900 af2a b602 30c0 03c4 3a25 2ab4
    0x0000810: 00e0 b603 c82a b401 e2b8 03a1 2ab4 01e4
    0x0000820: b803 a12a b401 e6b8 03a1 b603 ce3a 2618
    0x0000830: 1328 979e 0012 1926 b203 d4b9 03da 0200
    0x0000840: 3a26 a700 4418 1328 989c 0012 1926 b203
    0x0000850: ddb9 03da 0200 3a26 a700 2e18 1718 0697
    0x0000860: 9e00 1219 26b2 03e0 b903 da02 003a 26a7
    0x0000870: 0017 1817 1806 989c 000f 1926 b203 e3b9
    0x0000880: 03da 0200 3a26 1926 b903 e701 00b2 03ed
    0x0000890: a500 21bb 03ef 5919 2519 26b7 03f2 3a27
    0x00008a0: 2ab4 00e0 b600 e6b6 02d9 1927 b902 df02
    0x00008b0: 002a b603 f599 018a 2ab4 037a 9900 112a
    0x00008c0: b603 7d99 000a 2ac1 01a1 9a01 752a b602
    0x00008d0: 6b9a 016e 2ab4 01e2 180b 6739 4c2a b401
    0x00008e0: e418 0f67 394e 2ab4 01e6 1811 6739 2919
    0x00008f0: 4bb2 03fb a500 060e 394e 194b c600 162a
    0x0000900: b403 7a99 000f 194b 2ab4 00e0 1949 2ab6
    0x0000910: 03ff 2a2a b402 9b8d 184c 184c 6b18 2918
    0x0000920: 296b 63b8 0403 8d14 0404 6b63 90b5 029b
    0x0000930: 2a2a b404 078d 184c 184c 6b18 4e18 4e6b
    0x0000940: 6318 2918 296b 63b8 0403 8d14 0404 6b63
    0x0000950: 90b5 0407 2ab4 0407 2ab4 012e 8695 9e00
    0x0000960: b519 4ab9 040b 0100 b204 11a5 00a8 2a2a
    0x0000970: b404 078b 0460 b501 2e2a b604 1499 008b
    0x0000980: 2ab6 033c 9900 112a b604 17c6 000a 2ab6
    0x0000990: 0417 a700 042a 3a2b 192b 2aa6 0009 1304
    0x00009a0: 18a7 0006 1304 1938 2c19 2bb4 0371 192b
    0x00009b0: b403 716b 1404 1a6b 192b b403 7319 2bb4
    0x00009c0: 0373 6b63 192b b403 7519 2bb4 0375 6b14
    0x00009d0: 041a 6b63 b804 0317 2c6a 3850 1750 0c95
    0x00009e0: 9e00 060c 3850 2a2a b604 1f17 500c 2ab4
    0x00009f0: 0135 b604 222a b401 35b6 0422 6613 0419
    0x0000a00: 6a62 b604 26a7 003a 2a19 4919 4bb6 042a
    0x0000a10: a700 2f2a b404 072a b401 3095 9e00 232a
    0x0000a20: b604 2d99 001c 194a b904 0b01 00b2 0411
    0x0000a30: a600 0f2a 2a2a b404 07b6 0431 b501 30b8
    0x0000a40: 0436 2ab6 0439 3625 2ab4 00e0 2ab6 01f1
    0x0000a50: 1404 3ab6 043f b604 4299 0053 2a04 b604
    0x0000a60: 4515 259a 0059 2a59 b401 3b04 60b5 013b
    0x0000a70: 2ab4 013b 9a00 48bb 02d2 5901 2ab6 0230
    0x0000a80: 1008 b702 d53a 262a b400 e0b6 00e6 b602
    0x0000a90: d919 26b9 02df 0200 1926 b602 e49a 000c
    0x0000aa0: 2a19 26b6 02e7 b602 eaa7 0013 2ab4 013b
    0x0000ab0: 9d00 0c2a 2ab6 0139 74b5 013b 1525 9900
    0x0000ac0: 342a b604 4899 002d 2ab2 044e 1304 4f13
    0x0000ad0: 0450 2ab4 0135 b604 222a b401 35b6 0422
    0x0000ae0: 6613 0419 6a62 b604 262a 2ab6 0139 74b5
    0x0000af0: 013b 2ab4 00e0 b402 5bb6 028a b203 15b6
    0x0000b00: 0453 b1
  Exception Handler Table:
    bci [36, 40] => handler: 43
  Stackmap Table:
    same_frame(@36)
    same_locals_1_stack_item_frame(@43,Object[#786])
    same_frame(@81)
    same_frame(@116)
    full_frame(@156,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Long},{})
    same_frame_extended(@222)
    same_frame(@225)
    same_frame_extended(@295)
    same_frame(@298)
    same_frame(@306)
    full_frame(@369,{Object[#2],Object[#511],Double,Double,Double},{})
    full_frame(@449,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double},{})
    append_frame(@474,Double,Double,Double)
    append_frame(@500,Double)
    same_frame(@558)
    same_frame(@573)
    same_frame(@579)
    chop_frame(@585,1)
    same_frame(@648)
    same_frame(@666)
    same_frame(@674)
    same_frame(@681)
    same_frame_extended(@747)
    same_frame(@762)
    same_frame(@768)
    same_frame(@795)
    same_frame(@813)
    same_frame(@821)
    same_frame(@828)
    full_frame(@875,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer},{})
    chop_frame(@911,1)
    chop_frame(@926,1)
    append_frame(@944,Integer,Integer)
    chop_frame(@978,1)
    chop_frame(@998,1)
    append_frame(@1017,Integer,Integer)
    chop_frame(@1053,1)
    chop_frame(@1075,1)
    same_frame(@1097)
    same_frame(@1101)
    same_locals_1_stack_item_frame(@1102,Integer)
    append_frame(@1133,Integer)
    full_frame(@1220,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Integer},{})
    chop_frame(@1254,1)
    full_frame(@1281,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Top,Double,Integer,Integer},{})
    chop_frame(@1315,1)
    full_frame(@1342,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Top,Double,Integer,Top,Double,Integer,Integer},{})
    chop_frame(@1376,1)
    full_frame(@1409,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Top,Double,Integer,Top,Double,Integer,Object[#480],Double,Integer,Integer},{})
    chop_frame(@1443,1)
    full_frame(@1470,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Top,Double,Integer,Top,Double,Integer,Object[#480],Double,Integer,Top,Double,Integer,Integer},{})
    chop_frame(@1504,1)
    full_frame(@1531,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Top,Double,Double,Double,Object[#480],Object[#777],Object[#480],Object[#480],Double,Integer,Top,Double,Integer,Top,Double,Integer,Object[#480],Double,Integer,Top,Double,Integer,Top,Double,Integer,Integer},{})
    chop_frame(@1565,1)
    append_frame(@1631,Top,Double,Double)
    same_frame(@1649)
    append_frame(@1661,Integer,Integer)
    chop_frame(@1697,1)
    full_frame(@1753,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer},{})
    same_locals_1_stack_item_frame(@1796,Object[#2])
    same_locals_1_stack_item_frame(@1800,Object[#2])
    full_frame(@1801,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1817,Object[#2])
    full_frame(@1818,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1840,Object[#2])
    full_frame(@1841,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer},{Object[#2],Integer})
    same_locals_1_stack_item_frame(@1859,Object[#2])
    same_locals_1_stack_item_frame(@1863,Object[#2])
    full_frame(@1864,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer},{Object[#2],Integer})
    full_frame(@1962,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#948],Object[#954],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#28]},{})
    full_frame(@1970,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948]},{})
    same_frame(@1996)
    same_frame(@2009)
    append_frame(@2036,Object[#954])
    full_frame(@2117,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Object[#964],Object[#982],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954]},{})
    same_frame(@2139)
    same_frame(@2162)
    same_frame(@2182)
    full_frame(@2225,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954]},{})
    same_frame(@2253)
    full_frame(@2298,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954],Double,Double},{})
    same_frame(@2322)
    same_frame_extended(@2453)
    same_locals_1_stack_item_frame(@2454,Object[#2])
    full_frame(@2468,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Object[#2],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954],Double,Double},{})
    same_locals_1_stack_item_frame(@2471,Float)
    full_frame(@2534,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Object[#2],Float,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954],Double,Double,Float},{})
    full_frame(@2568,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Double,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954],Double,Double},{})
    same_frame(@2579)
    full_frame(@2623,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954]},{})
    full_frame(@2729,{Object[#2],Object[#511],Double,Double,Double,Top,Top,Top,Double,Top,Top,Double,Double,Double,Double,Double,Top,Top,Object[#777],Object[#480],Integer,Integer,Top,Top,Top,Top,Top,Top,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Integer,Object[#28],Object[#948],Object[#954]},{})
    same_frame(@2732)
    same_frame(@2748)
    same_frame(@2802)
    full_frame(@2812,{Object[#2],Object[#511],Double,Double,Double},{})

        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_371]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_371]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_371]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_371]
        at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:416) ~[vi.class:?]
        at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:282) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:783) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1707) ~[MinecraftServer.class:?]
        ... 17 more

**Comment by DJQ28** [comment]
It is likely a compatibility issue with catserver.
There is no problem loading using the original FORGE version.

Reported this to CATSERVER ISSUE
